version: "2.3"

services:

  node:
    image: ${DOCKER_IMAGE? Missing value for DOCKER_IMAGE env var!}
    build: .
    restart: always
    env_file:
      # ORDER OF THE ENV FILES MATTERS
      - .env.default
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${PUBLIC_DOMAIN? Missing value for: PUBLIC_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT? Missing value for: HTTP_PORT}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAIN}"

networks:
  traefik:
    external: true
