version: "2.3"

services:

  dev:
    image: ${DOCKER_IMAGE:-approov/demo-approov-io-shapes-api/${BUILD_RELEASE_FROM:-main}:dev}
    build:
      context: .
      args:
        BUILD_RELEASE_FROM: ${BUILD_RELEASE_FROM:-main} # pass through to container from .env file
    env_file:
      # ORDER OF THE ENV FILES MATTERS - definitions in later files override earlier ones.
      # No environment variables are inherited from the host environment.
      - .env.default
      - .env
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    ports:
      - 127.0.0.1:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    networks:
      - default

  node:
    image: ${DOCKER_IMAGE:-approov/demo-approov-io-shapes-api/${BUILD_RELEASE_FROM:-main}}
    build:
      context: .
      args:
        BUILD_RELEASE_FROM: ${BUILD_RELEASE_FROM:-main} # pass through to container from .env file
    restart: always
    env_file:
      # ORDER OF THE ENV FILES MATTERS - definitions in later files override earlier ones.
      # No environment variables are inherited from the host environment.
      - .env.default
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${PUBLIC_DOMAIN:-shapes.demo.approov.io,shapes.approov.io}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT:-8002}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAIN:-shapes.demo.approov.io,shapes.approov.io}"

networks:
  traefik:
    external: true
