version: "2.3"

services:

  dev:
    image: ${DOCKER_IMAGE:-approov2/shapes-node-koa:dev}
    build: .
    env_file:
      # ORDER OF THE ENV FILES MATTERS
      - .env.default
      - .env
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    ports:
      - 127.0.0.1:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    networks:
      - default

  node:
    image: ${DOCKER_IMAGE:-approov2/shapes-node-koa}
    build: .
    restart: always
    env_file:
      # ORDER OF THE ENV FILES MATTERS
      - .env.default
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${PUBLIC_DOMAIN? Missing value for: PUBLIC_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT:-8002}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAIN}"

networks:
  traefik:
    external: true
